name: data_notifier
description: "A Flutter package for managing and observing data changes in reactive and simple way."
version: 0.1.0
homepage: null

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
