name: data_notifier
description: "Manage and observe data states with ValueNotifier/ValueListenable. Handle loading, loaded, and error states with enhanced debugging."
version: 0.1.6

license: MIT
homepage: https://github.com/melihhakanpektas/data_notifier
repository: https://github.com/melihhakanpektas/data_notifier
issue_tracker: https://github.com/melihhakanpektas/data_notifier/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
